### PR TITLE
Remove newrelic

### PR DESCRIPTION
**Pull request by jamezpolley**

### CODE REVIEW

**Comment by jamezpolley** [comment]
@mlandauer points out that this increases divergence from upstream, which we want to avoid.

We can instead simply remove the newrelic licence key and this should disable newrelic.

**Comment by jamezpolley** [comment]
I'm reopening this because it turns out that removing the newrelic licence key *does not* disable newrelic. Even without a licence key, RTK and RTK Staging are each "costing" 144CU/day -> up to 9000CU/month, which is 3x our licenced 3000CU.

https://docs.newrelic.com/docs/agents/manage-apm-agents/installation/disable-apm-agent suggests that to disable the APM we need to uninstall the gem.

**Comment by mlandauer** [comment]
@jamezpolley that documentation you link to says:
> These methods will remove most instrumentation but there will still be a small amount of activity and overhead:
>    Use the `agent_enabled` configuration setting. This can be done in the configuration file or in the per-environment stanzas. Restart your app server afterward.
>    Do the same via an environment variable, then restart the app server.

Couldn't we just set the `agent_enabled` configuration setting in our ansible setup and that way not have to uninstall the gem?

**Comment by jamezpolley** [comment]
Hrm.

My interpretation of "small amount of activity and overhead" was that it would be what we're seeing now - the APM is connecting to NewRelic (and thus costing CUs) but not sending any data.

But I don't know that for sure - so it's worth testing out.

**Comment by jamezpolley** [comment]
Okay, initial indications are that "agent_enabled: false" does do the trick.

**Pull request closed without merging**
